---
policies:
  - type: commit
    spec:
      dco: true
      gpg:
        required: true
      header:
        length: 120
        imperative: true
        case: lower
        invalidLastCharacters: .
      body:
        required: false
      conventional:
        types: ["chore", "docs","ci","perf", "refactor", "style", "test", "release"]
        scopes: [".*"]