name: Release And Publish

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

env:
  MAVEN_CLI_OPTS: "--batch-mode --no-transfer-progress --errors --fail-at-end -Dstyle.color=always -DinstallAtEnd=true -DdeployAtEnd=true -s development/maven-gh-settings.xml"

jobs:
  release:
    runs-on: ubuntu-latest
    environment: mainenv
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0  # For changelog generation to have full history
      
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@cb9bde2e2525e640591a934b1fd28eef1dcaf5e5 # v6
        with:
          gpg_private_key: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
          passphrase: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true 

      - name: Set up Java
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          
      
      - name: Update POM version
        run: |
          echo "Tag: ${GITHUB_REF_NAME}"
          TAG="${GITHUB_REF_NAME#v}"
          echo "Version: ${TAG}"
          mvn $MAVEN_CLI_OPTS versions:set -DnewVersion=${TAG} -DgenerateBackupPoms=false -DskipTests
       
      - name: Generate a changelog
        uses: orhun/git-cliff-action@b946ed27a675d653b308f29a7bbad813b85bf7aa # v3
        with:
          config: development/gitcliff-gh-keepachangelog.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}
      # - name: Generate Changelog
      #   env:
      #     JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: mvn --batch-mode --no-transfer-progress -s $GITHUB_WORKSPACE/development/maven-gh-settings.xml jreleaser:changelog -DskipTests

      # - name: Move Changelog
      #   run: mv target/jreleaser/release/CHANGELOG.md ./CHANGELOG.md

      - name: Switch to main branch
        run: |
          git fetch origin main:main
          git checkout main
          git branch --set-upstream-to=origin/main main

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@e348103e9026cc0eee72ae06630dbe30c8bf7a79 # v5
        with:
          commit_message: |
            chore(release): ${{ github.ref_name }}
            
            Skip CI as this is an automated release commit.
            
            [skip ci]
          file_pattern: 'pom.xml CHANGELOG.md'
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_options: '--signoff'
          branch: main
          
      - name: Release with JReleaser
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
          M2_USER_NAME: ${{ secrets.M2_USER_NAME }}
          M2_ACCESS_TOKEN: ${{ secrets.M2_ACCESS_TOKEN }}
        run: mvn $MAVEN_CLI_OPTS deploy jreleaser:full-release -DskipTests
        
      - name: JReleaser output
        if: always()
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4
        with:
          name: jreleaser-logs
          path: |
            target/jreleaser/trace.log
            target/jreleaser/output.properties
