# SPDX-FileCopyrightText: 2024 Digg - The Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

name: eudiw-wallet-metadata-lib-poc workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  commitlint:
    uses: ./.github/workflows/commitlint.yml
  dependencyreviewlint:
    uses: ./.github/workflows/dependencyreview.yml
# license:
  #   uses: ./.github/workflows/license.yml
  misclint:
    permissions:
      contents: read
      security-events: write
    uses: ./.github/workflows/misclint.yml
  test:
    if: always() 
    permissions:
      contents: read
      packages: read
    #needs: [commitlint,license, misclint, dependencyreviewlint]
    needs: [commitlint, dependencyreviewlint]
    uses: ./.github/workflows/test.yml
